/*
 * pfmnav.c - Keyboard navigation array for the performance editor
 *
 * Copyright (c) 2006, 2015 Matt Gregory
 *
 * This file is part of TX81Z Programmer.
 *
 * TX81Z Programmer is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published by
 * the Free Software Foundation.
 *
 * TX81Z Programmer is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with TX81Z Programmer.  If not, see <http://www.gnu.org/licenses/>.
 */
#include "stdafx.h"
#include "resource.h"
#include "dlg/pfmnav.h"

/*
 * Global variables
 */
KEYNAV PfmNav_nav[] = {
    /* ctrlID, left, up, right, down */
    { IDC_PFM_NAME,         0,                    0,                    IDC_ASSIGN_MODE,      IDC_INST1_MAX_NOTES  },
    { IDC_ASSIGN_MODE,      IDC_PFM_NAME,         0,                    IDC_EFFECT_SELECT,    IDC_INST1_MAX_NOTES  },
    { IDC_EFFECT_SELECT,    IDC_ASSIGN_MODE,      0,                    IDC_MICROTUNE_TABLE,  IDC_INST2_MAX_NOTES  },
    { IDC_MICROTUNE_TABLE,  IDC_EFFECT_SELECT,    0,                    IDC_MICROTUNE_KEY,    IDC_INST3_MAX_NOTES  },
    { IDC_MICROTUNE_KEY,    IDC_MICROTUNE_TABLE,  0,                    0,                    IDC_INST4_MAX_NOTES  },
    { IDC_INST1_MAX_NOTES,  IDC_INST8_MAX_NOTES,  IDC_PFM_NAME,         IDC_INST2_MAX_NOTES,  IDC_INST1_VOICE_NUM  },
    { IDC_INST1_VOICE_NUM,  IDC_INST8_VOICE_NUM,  IDC_INST1_MAX_NOTES,  IDC_INST2_VOICE_NUM,  IDC_INST1_CHANNEL    },
    { IDC_INST1_CHANNEL,    IDC_INST8_CHANNEL,    IDC_INST1_VOICE_NUM,  IDC_INST2_CHANNEL,    IDC_INST1_LIMIT_L    },
    { IDC_INST1_LIMIT_L,    IDC_INST8_LIMIT_L,    IDC_INST1_CHANNEL,    IDC_INST2_LIMIT_L,    IDC_INST1_LIMIT_H    },
    { IDC_INST1_LIMIT_H,    IDC_INST8_LIMIT_H,    IDC_INST1_LIMIT_L,    IDC_INST2_LIMIT_H,    IDC_INST1_DETUNE     },
    { IDC_INST1_DETUNE,     IDC_INST8_DETUNE,     IDC_INST1_LIMIT_H,    IDC_INST2_DETUNE,     IDC_INST1_NOTE_SHIFT },
    { IDC_INST1_NOTE_SHIFT, IDC_INST8_NOTE_SHIFT, IDC_INST1_DETUNE,     IDC_INST2_NOTE_SHIFT, IDC_INST1_VOLUME     },
    { IDC_INST1_VOLUME,     IDC_INST8_VOLUME,     IDC_INST1_NOTE_SHIFT, IDC_INST2_VOLUME,     IDC_INST1_OUT_ASSIGN },
    { IDC_INST1_OUT_ASSIGN, IDC_INST8_OUT_ASSIGN, IDC_INST1_VOLUME,     IDC_INST2_OUT_ASSIGN, IDC_INST1_LFO_SELECT },
    { IDC_INST1_LFO_SELECT, IDC_INST8_LFO_SELECT, IDC_INST1_OUT_ASSIGN, IDC_INST2_LFO_SELECT, IDC_INST1_MICROTUNE  },
    { IDC_INST1_MICROTUNE,  IDC_INST8_MICROTUNE,  IDC_INST1_LFO_SELECT, IDC_INST2_MICROTUNE,  IDC_INST5_MAX_NOTES  },
    { IDC_INST2_MAX_NOTES,  IDC_INST1_MAX_NOTES,  IDC_ASSIGN_MODE,      IDC_INST3_MAX_NOTES,  IDC_INST2_VOICE_NUM  },
    { IDC_INST2_VOICE_NUM,  IDC_INST1_VOICE_NUM,  IDC_INST2_MAX_NOTES,  IDC_INST3_VOICE_NUM,  IDC_INST2_CHANNEL    },
    { IDC_INST2_CHANNEL,    IDC_INST1_CHANNEL,    IDC_INST2_VOICE_NUM,  IDC_INST3_CHANNEL,    IDC_INST2_LIMIT_L    },
    { IDC_INST2_LIMIT_L,    IDC_INST1_LIMIT_L,    IDC_INST2_CHANNEL,    IDC_INST3_LIMIT_L,    IDC_INST2_LIMIT_H    },
    { IDC_INST2_LIMIT_H,    IDC_INST1_LIMIT_H,    IDC_INST2_LIMIT_L,    IDC_INST3_LIMIT_H,    IDC_INST2_DETUNE     },
    { IDC_INST2_DETUNE,     IDC_INST1_DETUNE,     IDC_INST2_LIMIT_H,    IDC_INST3_DETUNE,     IDC_INST2_NOTE_SHIFT },
    { IDC_INST2_NOTE_SHIFT, IDC_INST1_NOTE_SHIFT, IDC_INST2_DETUNE,     IDC_INST3_NOTE_SHIFT, IDC_INST2_VOLUME     },
    { IDC_INST2_VOLUME,     IDC_INST1_VOLUME,     IDC_INST2_NOTE_SHIFT, IDC_INST3_VOLUME,     IDC_INST2_OUT_ASSIGN },
    { IDC_INST2_OUT_ASSIGN, IDC_INST1_OUT_ASSIGN, IDC_INST2_VOLUME,     IDC_INST3_OUT_ASSIGN, IDC_INST2_LFO_SELECT },
    { IDC_INST2_LFO_SELECT, IDC_INST1_LFO_SELECT, IDC_INST2_OUT_ASSIGN, IDC_INST3_LFO_SELECT, IDC_INST2_MICROTUNE  },
    { IDC_INST2_MICROTUNE,  IDC_INST1_MICROTUNE,  IDC_INST2_LFO_SELECT, IDC_INST3_MICROTUNE,  IDC_INST6_MAX_NOTES  },
    { IDC_INST3_MAX_NOTES,  IDC_INST2_MAX_NOTES,  IDC_MICROTUNE_TABLE,  IDC_INST4_MAX_NOTES,  IDC_INST3_VOICE_NUM  },
    { IDC_INST3_VOICE_NUM,  IDC_INST2_VOICE_NUM,  IDC_INST3_MAX_NOTES,  IDC_INST4_VOICE_NUM,  IDC_INST3_CHANNEL    },
    { IDC_INST3_CHANNEL,    IDC_INST2_CHANNEL,    IDC_INST3_VOICE_NUM,  IDC_INST4_CHANNEL,    IDC_INST3_LIMIT_L    },
    { IDC_INST3_LIMIT_L,    IDC_INST2_LIMIT_L,    IDC_INST3_CHANNEL,    IDC_INST4_LIMIT_L,    IDC_INST3_LIMIT_H    },
    { IDC_INST3_LIMIT_H,    IDC_INST2_LIMIT_H,    IDC_INST3_LIMIT_L,    IDC_INST4_LIMIT_H,    IDC_INST3_DETUNE     },
    { IDC_INST3_DETUNE,     IDC_INST2_DETUNE,     IDC_INST3_LIMIT_H,    IDC_INST4_DETUNE,     IDC_INST3_NOTE_SHIFT },
    { IDC_INST3_NOTE_SHIFT, IDC_INST2_NOTE_SHIFT, IDC_INST3_DETUNE,     IDC_INST4_NOTE_SHIFT, IDC_INST3_VOLUME     },
    { IDC_INST3_VOLUME,     IDC_INST2_VOLUME,     IDC_INST3_NOTE_SHIFT, IDC_INST4_VOLUME,     IDC_INST3_OUT_ASSIGN },
    { IDC_INST3_OUT_ASSIGN, IDC_INST2_OUT_ASSIGN, IDC_INST3_VOLUME,     IDC_INST4_OUT_ASSIGN, IDC_INST3_LFO_SELECT },
    { IDC_INST3_LFO_SELECT, IDC_INST2_LFO_SELECT, IDC_INST3_OUT_ASSIGN, IDC_INST4_LFO_SELECT, IDC_INST3_MICROTUNE  },
    { IDC_INST3_MICROTUNE,  IDC_INST2_MICROTUNE,  IDC_INST3_LFO_SELECT, IDC_INST4_MICROTUNE,  IDC_INST7_MAX_NOTES  },
    { IDC_INST4_MAX_NOTES,  IDC_INST3_MAX_NOTES,  IDC_MICROTUNE_KEY,    IDC_INST5_MAX_NOTES,  IDC_INST4_VOICE_NUM  },
    { IDC_INST4_VOICE_NUM,  IDC_INST3_VOICE_NUM,  IDC_INST4_MAX_NOTES,  IDC_INST5_VOICE_NUM,  IDC_INST4_CHANNEL    },
    { IDC_INST4_CHANNEL,    IDC_INST3_CHANNEL,    IDC_INST4_VOICE_NUM,  IDC_INST5_CHANNEL,    IDC_INST4_LIMIT_L    },
    { IDC_INST4_LIMIT_L,    IDC_INST3_LIMIT_L,    IDC_INST4_CHANNEL,    IDC_INST5_LIMIT_L,    IDC_INST4_LIMIT_H    },
    { IDC_INST4_LIMIT_H,    IDC_INST3_LIMIT_H,    IDC_INST4_LIMIT_L,    IDC_INST5_LIMIT_H,    IDC_INST4_DETUNE     },
    { IDC_INST4_DETUNE,     IDC_INST3_DETUNE,     IDC_INST4_LIMIT_H,    IDC_INST5_DETUNE,     IDC_INST4_NOTE_SHIFT },
    { IDC_INST4_NOTE_SHIFT, IDC_INST3_NOTE_SHIFT, IDC_INST4_DETUNE,     IDC_INST5_NOTE_SHIFT, IDC_INST4_VOLUME     },
    { IDC_INST4_VOLUME,     IDC_INST3_VOLUME,     IDC_INST4_NOTE_SHIFT, IDC_INST5_VOLUME,     IDC_INST4_OUT_ASSIGN },
    { IDC_INST4_OUT_ASSIGN, IDC_INST3_OUT_ASSIGN, IDC_INST4_VOLUME,     IDC_INST5_OUT_ASSIGN, IDC_INST4_LFO_SELECT },
    { IDC_INST4_LFO_SELECT, IDC_INST3_LFO_SELECT, IDC_INST4_OUT_ASSIGN, IDC_INST5_LFO_SELECT, IDC_INST4_MICROTUNE  },
    { IDC_INST4_MICROTUNE,  IDC_INST3_MICROTUNE,  IDC_INST4_LFO_SELECT, IDC_INST5_MICROTUNE,  IDC_INST8_MAX_NOTES  },
    { IDC_INST5_MAX_NOTES,  IDC_INST4_MAX_NOTES,  IDC_INST1_MICROTUNE,  IDC_INST6_MAX_NOTES,  IDC_INST5_VOICE_NUM  },
    { IDC_INST5_VOICE_NUM,  IDC_INST4_VOICE_NUM,  IDC_INST5_MAX_NOTES,  IDC_INST6_VOICE_NUM,  IDC_INST5_CHANNEL    },
    { IDC_INST5_CHANNEL,    IDC_INST4_CHANNEL,    IDC_INST5_VOICE_NUM,  IDC_INST6_CHANNEL,    IDC_INST5_LIMIT_L    },
    { IDC_INST5_LIMIT_L,    IDC_INST4_LIMIT_L,    IDC_INST5_CHANNEL,    IDC_INST6_LIMIT_L,    IDC_INST5_LIMIT_H    },
    { IDC_INST5_LIMIT_H,    IDC_INST4_LIMIT_H,    IDC_INST5_LIMIT_L,    IDC_INST6_LIMIT_H,    IDC_INST5_DETUNE     },
    { IDC_INST5_DETUNE,     IDC_INST4_DETUNE,     IDC_INST5_LIMIT_H,    IDC_INST6_DETUNE,     IDC_INST5_NOTE_SHIFT },
    { IDC_INST5_NOTE_SHIFT, IDC_INST4_NOTE_SHIFT, IDC_INST5_DETUNE,     IDC_INST6_NOTE_SHIFT, IDC_INST5_VOLUME     },
    { IDC_INST5_VOLUME,     IDC_INST4_VOLUME,     IDC_INST5_NOTE_SHIFT, IDC_INST6_VOLUME,     IDC_INST5_OUT_ASSIGN },
    { IDC_INST5_OUT_ASSIGN, IDC_INST4_OUT_ASSIGN, IDC_INST5_VOLUME,     IDC_INST6_OUT_ASSIGN, IDC_INST5_LFO_SELECT },
    { IDC_INST5_LFO_SELECT, IDC_INST4_LFO_SELECT, IDC_INST5_OUT_ASSIGN, IDC_INST6_LFO_SELECT, IDC_INST5_MICROTUNE  },
    { IDC_INST5_MICROTUNE,  IDC_INST4_MICROTUNE,  IDC_INST5_LFO_SELECT, IDC_INST6_MICROTUNE,  0,                   },
    { IDC_INST6_MAX_NOTES,  IDC_INST5_MAX_NOTES,  IDC_INST2_MICROTUNE,  IDC_INST7_MAX_NOTES,  IDC_INST6_VOICE_NUM  },
    { IDC_INST6_VOICE_NUM,  IDC_INST5_VOICE_NUM,  IDC_INST6_MAX_NOTES,  IDC_INST7_VOICE_NUM,  IDC_INST6_CHANNEL    },
    { IDC_INST6_CHANNEL,    IDC_INST5_CHANNEL,    IDC_INST6_VOICE_NUM,  IDC_INST7_CHANNEL,    IDC_INST6_LIMIT_L    },
    { IDC_INST6_LIMIT_L,    IDC_INST5_LIMIT_L,    IDC_INST6_CHANNEL,    IDC_INST7_LIMIT_L,    IDC_INST6_LIMIT_H    },
    { IDC_INST6_LIMIT_H,    IDC_INST5_LIMIT_H,    IDC_INST6_LIMIT_L,    IDC_INST7_LIMIT_H,    IDC_INST6_DETUNE     },
    { IDC_INST6_DETUNE,     IDC_INST5_DETUNE,     IDC_INST6_LIMIT_H,    IDC_INST7_DETUNE,     IDC_INST6_NOTE_SHIFT },
    { IDC_INST6_NOTE_SHIFT, IDC_INST5_NOTE_SHIFT, IDC_INST6_DETUNE,     IDC_INST7_NOTE_SHIFT, IDC_INST6_VOLUME     },
    { IDC_INST6_VOLUME,     IDC_INST5_VOLUME,     IDC_INST6_NOTE_SHIFT, IDC_INST7_VOLUME,     IDC_INST6_OUT_ASSIGN },
    { IDC_INST6_OUT_ASSIGN, IDC_INST5_OUT_ASSIGN, IDC_INST6_VOLUME,     IDC_INST7_OUT_ASSIGN, IDC_INST6_LFO_SELECT },
    { IDC_INST6_LFO_SELECT, IDC_INST5_LFO_SELECT, IDC_INST6_OUT_ASSIGN, IDC_INST7_LFO_SELECT, IDC_INST6_MICROTUNE  },
    { IDC_INST6_MICROTUNE,  IDC_INST5_MICROTUNE,  IDC_INST6_LFO_SELECT, IDC_INST7_MICROTUNE,  0,                   },
    { IDC_INST7_MAX_NOTES,  IDC_INST6_MAX_NOTES,  IDC_INST3_MICROTUNE,  IDC_INST8_MAX_NOTES,  IDC_INST7_VOICE_NUM  },
    { IDC_INST7_VOICE_NUM,  IDC_INST6_VOICE_NUM,  IDC_INST7_MAX_NOTES,  IDC_INST8_VOICE_NUM,  IDC_INST7_CHANNEL    },
    { IDC_INST7_CHANNEL,    IDC_INST6_CHANNEL,    IDC_INST7_VOICE_NUM,  IDC_INST8_CHANNEL,    IDC_INST7_LIMIT_L    },
    { IDC_INST7_LIMIT_L,    IDC_INST6_LIMIT_L,    IDC_INST7_CHANNEL,    IDC_INST8_LIMIT_L,    IDC_INST7_LIMIT_H    },
    { IDC_INST7_LIMIT_H,    IDC_INST6_LIMIT_H,    IDC_INST7_LIMIT_L,    IDC_INST8_LIMIT_H,    IDC_INST7_DETUNE     },
    { IDC_INST7_DETUNE,     IDC_INST6_DETUNE,     IDC_INST7_LIMIT_H,    IDC_INST8_DETUNE,     IDC_INST7_NOTE_SHIFT },
    { IDC_INST7_NOTE_SHIFT, IDC_INST6_NOTE_SHIFT, IDC_INST7_DETUNE,     IDC_INST8_NOTE_SHIFT, IDC_INST7_VOLUME     },
    { IDC_INST7_VOLUME,     IDC_INST6_VOLUME,     IDC_INST7_NOTE_SHIFT, IDC_INST8_VOLUME,     IDC_INST7_OUT_ASSIGN },
    { IDC_INST7_OUT_ASSIGN, IDC_INST6_OUT_ASSIGN, IDC_INST7_VOLUME,     IDC_INST8_OUT_ASSIGN, IDC_INST7_LFO_SELECT },
    { IDC_INST7_LFO_SELECT, IDC_INST6_LFO_SELECT, IDC_INST7_OUT_ASSIGN, IDC_INST8_LFO_SELECT, IDC_INST7_MICROTUNE  },
    { IDC_INST7_MICROTUNE,  IDC_INST6_MICROTUNE,  IDC_INST7_LFO_SELECT, IDC_INST8_MICROTUNE,  0,                   },
    { IDC_INST8_MAX_NOTES,  IDC_INST7_MAX_NOTES,  IDC_INST4_MICROTUNE,  IDC_INST1_MAX_NOTES,  IDC_INST8_VOICE_NUM  },
    { IDC_INST8_VOICE_NUM,  IDC_INST7_VOICE_NUM,  IDC_INST8_MAX_NOTES,  IDC_INST1_VOICE_NUM,  IDC_INST8_CHANNEL    },
    { IDC_INST8_CHANNEL,    IDC_INST7_CHANNEL,    IDC_INST8_VOICE_NUM,  IDC_INST1_CHANNEL,    IDC_INST8_LIMIT_L    },
    { IDC_INST8_LIMIT_L,    IDC_INST7_LIMIT_L,    IDC_INST8_CHANNEL,    IDC_INST1_LIMIT_L,    IDC_INST8_LIMIT_H    },
    { IDC_INST8_LIMIT_H,    IDC_INST7_LIMIT_H,    IDC_INST8_LIMIT_L,    IDC_INST1_LIMIT_H,    IDC_INST8_DETUNE     },
    { IDC_INST8_DETUNE,     IDC_INST7_DETUNE,     IDC_INST8_LIMIT_H,    IDC_INST1_DETUNE,     IDC_INST8_NOTE_SHIFT },
    { IDC_INST8_NOTE_SHIFT, IDC_INST7_NOTE_SHIFT, IDC_INST8_DETUNE,     IDC_INST1_NOTE_SHIFT, IDC_INST8_VOLUME     },
    { IDC_INST8_VOLUME,     IDC_INST7_VOLUME,     IDC_INST8_NOTE_SHIFT, IDC_INST1_VOLUME,     IDC_INST8_OUT_ASSIGN },
    { IDC_INST8_OUT_ASSIGN, IDC_INST7_OUT_ASSIGN, IDC_INST8_VOLUME,     IDC_INST1_OUT_ASSIGN, IDC_INST8_LFO_SELECT },
    { IDC_INST8_LFO_SELECT, IDC_INST7_LFO_SELECT, IDC_INST8_OUT_ASSIGN, IDC_INST1_LFO_SELECT, IDC_INST8_MICROTUNE  },
    { IDC_INST8_MICROTUNE,  IDC_INST7_MICROTUNE,  IDC_INST8_LFO_SELECT, IDC_INST1_MICROTUNE,  0,                   },
};
const int PfmNav_navCnt = ARRAYSIZE(PfmNav_nav);

